IVDEPTH = ..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = overrideClassGenerator

CXXFILES = OverrideClassGenerator.cpp

#LLDLIBS = -lInventor -lInventorXt
LLDLIBS = $(INVENTOR_LIB)

all: all_ivbin

include $(IVCOMMONRULES)
