IVDEPTH = ..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivperf

CXXFILES = ivperf.cpp SbProfiler.cpp OverrideNodes.cpp BarChart.cpp ../make/Common.cpp

LLDLIBS = $(INVENTOR_LIB) $(INVENTOR_XT_LIB)

all: all_ivbin

install: install_ivbin

include $(IVCOMMONRULES)
