IVDEPTH = ..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivcat

CXXFILES = ivcat.cpp ../make/Common.cpp

LLDLIBS = $(INVENTOR_LIB)

all: all_ivbin

install: install_ivbin

include $(IVCOMMONRULES)
