IVDEPTH = ..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivgraph

CXXFILES = ivgraph.cpp ../make/Common.cpp

LLDLIBS = $(INVENTOR_LIB)

all: all_ivbin

install: install_ivbin

include $(IVCOMMONRULES)
